### ISSUE TITLE
How to get Randomsecret

### ISSUE THREAD

**Issue by nimboya** [phedoreanu/rancher-auto-redeploy#2]
Where can I get this value, is it from Dockerhub? Can you share the URL i can get this secret from so i can use, thank you

 DOCKER_HUB_KEY: randomsecret

**Comment by phedoreanu** [comment]
It can be anything you want. Make sure it's the same on both sides.

**Comment by nimboya** [comment]
Thank you very much. Nice work done. I wish to contribute too and improve documentation too. Expect my PR soon
